# Generated by Django 3.1.5 on 2021-01-30 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_favorited',
            new_name='is_favorite',
        ),
    ]
